"""Add full_name to SuperAdmin.

Revision ID: 945f8533c50d Revises: 4b5f455a555c Create Date: 2025-03-31 15:45:07.843272
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "945f8533c50d"
down_revision = "4b5f455a555c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cfdi_history_id", table_name="cfdi_history")
    op.drop_index("ix_cfdi_history_uuid", table_name="cfdi_history")
    op.drop_table("cfdi_history")
    op.create_foreign_key(None, "api_tokens", "users", ["user_id"], ["id"])
    op.add_column("superadmins", sa.Column("full_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("superadmins", "full_name")
    op.drop_constraint(None, "api_tokens", type_="foreignkey")
    op.create_table(
        "cfdi_history",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("uuid", sa.VARCHAR(), nullable=False),
        sa.Column("emisor_rfc", sa.VARCHAR(), nullable=False),
        sa.Column("receptor_rfc", sa.VARCHAR(), nullable=False),
        sa.Column("total", sa.VARCHAR(), nullable=False),
        sa.Column("estado", sa.VARCHAR(), nullable=True),
        sa.Column("es_cancelable", sa.VARCHAR(), nullable=True),
        sa.Column("estatus_cancelacion", sa.VARCHAR(), nullable=True),
        sa.Column("codigo_estatus", sa.VARCHAR(), nullable=True),
        sa.Column("validacion_efos", sa.VARCHAR(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cfdi_history_uuid", "cfdi_history", ["uuid"], unique=False)
    op.create_index("ix_cfdi_history_id", "cfdi_history", ["id"], unique=False)
    # ### end Alembic commands ###
